// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRecentFiles():Promise<Array<string>>;

export function LoadSettings():Promise<main.AppSettings>;

export function OpenFileDialog():Promise<Array<number>>;

export function OpenRecentFile(arg1:string):Promise<Array<number>>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;
